{% set name = "hmmlearn" %}
{% set version = "0.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6b4b2720f27af75da9367ab4d90dcb00f38da33168df6d917f9ec5de6670f6e1

build:
  number: 0
  skip: true  # [py<35]
  script:
    - {{ PYTHON }} setup.py build_ext
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv  # [unix]
    - {{ PYTHON }} setup.py install --single-version-externally-managed --record record.txt  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - numpy
    - cython
    - setuptools
    - setuptools_scm
  run:
    - python
    - scikit-learn >=0.16
    - {{ pin_compatible('numpy') }}
    - scipy >=0.19.0
    - setuptools
    - matplotlib-base >=1.1.1

test:
  imports:
    - hmmlearn
    - hmmlearn.tests

about:
  home: https://github.com/hmmlearn/hmmlearn
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Hidden Markov Models in Python with scikit-learn like API.
  doc_url: https://hmmlearn.readthedocs.io/en/stable/
  dev_url: https://hmmlearn.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - npavlovikj
    - njzjz
