appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: aVSM/vRAbtIRzeh603emdFh8/5nwBVCUQ7zRLDn+ePKr8cT7gu+pAPepMoFIkNMFB/OiKKyKgG/4DfJH3uVpcf/ZIK0CytG6jodlMTylCu9qV5Vn9y8YfSXYkVRQi2whLGN1IwFDwG/pWdIyKTs0yF4zVa7aa0Xfaq4o7ugDD2WsMhw89JcuI+VzQrmXLUbeDCxKWfelSNnoWBv/guDw/ldwjr+V/3RgnRLGqPpvHT8cMkphNUvJL5xv29MOiS706tZADfNRbqeMrlGIYGdTHeyq8O4fG791ldUwQHW9Sc4pTqrhqAVHV0NZ9xYjHwAD3bCDs3YfA15TZ8+jEs5lG48AEYLmCrmRvoxRGs/HQ96myXC+Cq2Oz9oC3kqHn+uwrVu9y4PXWt9N2JqP/mMf7EnfQ8Lim0ASQZV7q6Qgahls0upGgPaZj7k9nsSA00EBz5wHaIv4Gf+pnbTkrgpOQSNkXMHt7wx+tXHTS3owuPHruQGooadd7OgyXdviyJvy2ZYhOJAO7i9+ayKDaK4UTQZa21lO1QP0yP3+SSUCpiQdM3+d57H/B12LMEtxcLfIelmueojapReAPe+JJd9Hrpc/XhG3PGb6wH4ei1Kmc4e+PIPsN8Q6prYzD79BkJ/ax+8XL8Gnuscdnf3eOlufqlLL905qXDFkqpicVdKrbaY=}
provider:
  win: azure
